// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: filterMessage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxPriceUSD float64 `protobuf:"fixed64,1,opt,name=maxPriceUSD,proto3" json:"maxPriceUSD,omitempty"`
	MinCPUCores uint32  `protobuf:"varint,2,opt,name=minCPUCores,proto3" json:"minCPUCores,omitempty"`
	MinCPUGhz   float64 `protobuf:"fixed64,3,opt,name=minCPUGhz,proto3" json:"minCPUGhz,omitempty"`
	Memory      *Memory `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filterMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_filterMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_filterMessage_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetMaxPriceUSD() float64 {
	if x != nil {
		return x.MaxPriceUSD
	}
	return 0
}

func (x *Filter) GetMinCPUCores() uint32 {
	if x != nil {
		return x.MinCPUCores
	}
	return 0
}

func (x *Filter) GetMinCPUGhz() float64 {
	if x != nil {
		return x.MinCPUGhz
	}
	return 0
}

func (x *Filter) GetMemory() *Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_filterMessage_proto protoreflect.FileDescriptor

var file_filterMessage_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x65, 0x6d, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x13, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x63, 0x65, 0x55, 0x53,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x55, 0x53, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x43, 0x50, 0x55, 0x43, 0x6f,
	0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x69, 0x6e, 0x43, 0x50,
	0x55, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x43, 0x50, 0x55,
	0x47, 0x68, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6d, 0x69, 0x6e, 0x43, 0x50,
	0x55, 0x47, 0x68, 0x7a, 0x12, 0x2b, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x65, 0x6d, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_filterMessage_proto_rawDescOnce sync.Once
	file_filterMessage_proto_rawDescData = file_filterMessage_proto_rawDesc
)

func file_filterMessage_proto_rawDescGZIP() []byte {
	file_filterMessage_proto_rawDescOnce.Do(func() {
		file_filterMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_filterMessage_proto_rawDescData)
	})
	return file_filterMessage_proto_rawDescData
}

var file_filterMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_filterMessage_proto_goTypes = []interface{}{
	(*Filter)(nil), // 0: demoMessage.Filter
	(*Memory)(nil), // 1: demoMessage.Memory
}
var file_filterMessage_proto_depIdxs = []int32{
	1, // 0: demoMessage.Filter.memory:type_name -> demoMessage.Memory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_filterMessage_proto_init() }
func file_filterMessage_proto_init() {
	if File_filterMessage_proto != nil {
		return
	}
	file_memoryMessage_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_filterMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filterMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_filterMessage_proto_goTypes,
		DependencyIndexes: file_filterMessage_proto_depIdxs,
		MessageInfos:      file_filterMessage_proto_msgTypes,
	}.Build()
	File_filterMessage_proto = out.File
	file_filterMessage_proto_rawDesc = nil
	file_filterMessage_proto_goTypes = nil
	file_filterMessage_proto_depIdxs = nil
}
